- name: Download GPG keys to keyrings directory (Debian family)
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/share/keyrings/{{ item.filename }}"
    mode: '0644'
  loop: "{{ gpg_keys }}"
  when: ansible_os_family == "Debian"